[update to 19.1] Address review comment: make two methods static.
Albert Tugushev (2):
      Use is_artifact prop instead of scheme checking
      Fix option name for smart quotes in sphinxdoc conf (#6422)

Alex Loosley (1):
      Fix #5889: AttributeError: 'NoneType' object has no attribute 'netloc' (#6336)

Andy Freeland (1):
      Fix NameError when handling InvalidRequirement in install_req_from_req_string (#6419)

Anthony Sottile (6):
      delete some dead code
      Remove progress bar types
      Remove read_text_file
      Remove has_requirements
      Remove _copy_dist_from_dir
      Remove hidden

Benoit Pierre (1):
      improve handling of file URIs

Caleb Martinez (1):
      Allow adding a custom string to pip's User-Agent via an environment variable (#5550)

Chih-Hsuan Yen (2):
      Ensure all pip._vendor.* modules are mapped to debundled correspondences (#6113)
      Fix handling of requests exceptions when dependencies are debundled

Chris Jerdonek (44):
      Change the default of call_subprocess()'s show_stdout from True to False.
      Add back a test of call_subprocess() with no keyword arguments.
      Include in pip's User-Agent whether it looks like pip is in CI.
      Address review comments.
      Add log divider variable.
      Add format_command_args() with tests.
      Change format_command() to use shlex.quote().
      Change format_command_result() to use format_command_args().
      Prefix warning and error log messages.
      Refactor out build_wheels(), and test.
      Whether to build wheels is no longer affected by --no-cache-dir.
      Implement get_src_requirement() in the VersionControl base class.
      Move get_src_requirement() before the __init__ method.
      Move make_vcs_requirement_url() to vcs/__init__.py.
      Improve the call_subprocess() tests.
      Fix a couple spinner edge cases.
      Refactor out read_pyproject_toml() and resolve_pyproject_toml().
      Error out if installing a pyproject.toml-style (PEP 517) project in editable mode.
      Make VersionControl.get_netloc_and_auth() a class method.
      Make VersionControl.get_url_rev_and_auth() a class method.
      Make VersionControl.make_rev_args() a class method.
      Make VersionControl.get_base_rev_args() a class method.
      Change RevOptions to accept a VersionControl subclass.
      Allow finer-grained testing of subprocess stderr.
      Address review comment: make two methods static.
      Address review comments, and add tests.
      Make get_revision_sha() a class method.
      Make resolve_revision() a class method.
      Make is_commit_id_equal() a class method.
      Make get_current_branch() a class method.
      Make update_submodules() a class method.
      Make fetch_new() a class method.
      Make compare_urls() a class method.
      Prevent subprocess stdout and stderr from cluttering pip's stdout.
      Make deprecated_python cause allow_stderr_warning not expect_stderr.
      Remove logic for SSLContext warning on old versions of Python.
      Make expect_stderr mean the weaker allow_stderr_warning.
      Disallow two more argument combinations, and test.
      Pin pytest-rerunfailures to < 7.0 in tests-requirements.txt.
      Refactor install_backend_dependencies() out from prep_for_dist().
      Require --no-use-pep517 if using editable mode with pyproject.toml.
      Enable test by fixing typo: "est_link_..." -> "test_link_..."
      Pin pytest-xdist to < 1.28.0 in tests-requirements.txt.
      Add CandidateEvaluator class to encapsulate sorting. (#6424)

Clark Boylan (1):
      Consistently catch exceptions in index.py

Daniele Esposti (1):
      Redact the password from the extra index URL in log messages (#6295)

Donald Stufft (2):
      Upgrade vendored dependencies
      Bump to 19.1

Jelmer Vernooĳ (3):
      Bazaar: Export directly from the remote branch.
      Make sure that bzr is available when running under Travis.
      Add tests for export with revision in the URL.

Jon Dufresne (1):
      Replace six.next() with builtin next()

Juanjo Bazán (1):
      Fix typo (extra parenthesis). (#6316)

Maxim Kurnikov (13):
      finish types for pip._internal.req, disallow untyped defs
      sort imports under TYPE_CHECKING alphabetically
      update mypy to 0.670
      rename variable to fix mypy redefinition error
      remove unused # type: ignore
      update flake8 to 3.7.6
      fix indentation errors
      ignore W504
      remove #noqa: F401
      remove unused exc variable
      remove unused imports
      add type annotations to StashedUninstallPathSet
      add missing trailing commas on multiline imports

Miro Hrončok (3):
      Mark 3 tests as network tests
      Fix utils.encoding.auto_decode() LookupError  with invalid encodings
      Pytest: Use get_closest_marker

Nicolas Bock (1):
      Do not clean base_url

Paul Moore (4):
      Reject --build-options for PEP 517 builds
      Stupid typo
      Add a news fragment
      Make flake8 shut up

Pi Delport (1):
      Fix some typos

Pradyun Gedam (2):
      Bump for development
      Remove note about flake8 noqa comments

Quentin Pradet (3):
      Update progress to 1.5
      Remove helpers.py from progress vendor
      Add news entry for progress 1.5 update

Steve Dower (1):
      Configuration files may now also be stored under `sys.prefix` (#6268)

Tzu-ping Chung (2):
      Isolate, reuse PackageFinder best candidate logic (#5971)
      Finder found candidates cleanup (#6415)

Xavier Fernandez (1):
      Tweak tests & url_to_path after review

jakirkham (1):
      Remove extra `.`

johnthagen (1):
      Add Subversion.get_vcs_version method (#6390)